name = "Stormland"
author = "Kermannne"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4440685f6de943caf811dc2b94bd0dc06578eae187527afced86fa92fe50436"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
