name = "Stormland"
author = "Kermannne & otomir23"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0d1216a57090dbf3352458d999253db2f8f2dedca02ca0e4145b7b189e8ddee"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
