name = "Stormland"
author = "Kermannne"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5c441f8c700506412173246020f5eeb9f1905015819d84dbf657aa00d7e4e9d"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
