name = "Stormland"
author = "Kermannne"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c2e36662606fdf2cb45ec630c03f6a9493b91f38b6f814611e55ba15e6ed635"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
